SELECT count(*) FROM Applications;

SELECT * FROM Applications TABLESAMPLE BERNOULLI (1)
LIMIT 20;

SELECT Essay FROM Entrants TABLESAMPLE BERNOULLI (1)
LIMIT 20;

SELECT * FROM Learning_Directions TABLESAMPLE BERNOULLI (1)
LIMIT 20;

SELECT * FROM Educational_Places TABLESAMPLE BERNOULLI (1)
LIMIT 20;